### ISSUE TITLE
Thumbnail is not loading in player.

### ISSUE THREAD

**Issue by jariwalabhavesh** [manse/react-native-brightcove-player#11]
I am trying to play audio in the player so i had just uploaded audio to brightcove account and set it id as videoId in player and it start playing in player but it had not load any thumbnail that i had uploaded with audio in brightcove it is just showing black and playing audio.

If i try the publish url on chrome then it is showing uploaded thumbnail and start playing audio.

Any idea why it is happening , I had also ask to brightcove support they said that audio will support in same brightcove player it will show uploaded thumbnail instead of video and will play audio.

**Comment by manse** [comment]
Then try uploading mp4 with still image.
With ffmpeg, you can make movies from an image and an audio.
https://superuser.com/questions/1041816/combine-one-image-one-audio-file-to-make-one-video-using-ffmpeg
