### ISSUE TITLE
Absolute Positioned Custom controls layer hides behind the Player in Android

### ISSUE THREAD

**Issue by sahil6111** [manse/react-native-brightcove-player#14]
I have added an Absolute positioned custom controls layer above the player but it is rendered behind the player in android but works perfectly in ios.
How can this be achieved in Android ?
Any suggestions @manse

**Comment by manse** [comment]
There is probably no way to solve the problem.
Please lay out your own controls so that it does not overlap the player.

**Comment by nlabofa** [comment]
This issue still occurs . Is there a solution to this @manse
