### ISSUE TITLE
Unable to create Archive/Release build for IOS

### ISSUE THREAD

**Issue by sahil6111** [manse/react-native-brightcove-player#15]
I am trying to create archive of my project which has **react-native-brightcove-player** integrated.
Build Succeeded in development, but when creating archive the **Build Failed** with below error:
`ld: library not found for -lreact-native-brightcove-player
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

![screen shot 2018-08-03 at 1 49 19 pm](https://user-images.githubusercontent.com/12442974/43632559-2188bcb2-9724-11e8-87e5-7395ec4269d1.png)

@manse Have you encountered this error while creating Archive/Release build?
Any suggestions would be a great help.

**Comment by manse** [comment]
I have not seen that error.
Please try the installation in the README again. 
https://github.com/manse/react-native-brightcove-player#installation

**Comment by sahil6111** [comment]
I have followed the Installation steps, everything is working in development. But when creating archive from xcode Build fails with library not found error.

**Comment by sahil6111** [comment]
Also i have tried to create archive of the example project in the repo. It also gives the same error **library not found**

**Comment by manse** [comment]
Come to think of it, it was impossible to compile for iOS 10.
Please set deployment target version to iOS 11?

**Comment by sahil6111** [comment]
Awesome, it's working after changing the deployment target version to iOS 11.
It would be nice to mention that in Documentation.

**Comment by manse** [comment]
Congrats!🎉 
I listed required OS versions in the README. Thank you! 😃

**Comment by technoplato** [comment]
@sahil6111 @manse Where do you update deployment target versions in XCode?

**Comment by jariwalabhavesh** [comment]
@technoplato : open your project in Xcode. Click on your project in the left panel, it will show a general setting on the right side.

General > deployment info > Deployments target

<img width="901" alt="screen shot 2018-11-13 at 11 59 55 am" src="https://user-images.githubusercontent.com/10993666/48395050-e4a67100-e73b-11e8-8d61-cc82a1348579.png">

**Comment by technoplato** [comment]
Thank you very much @jariwalabhavesh. As a Native Android developer, I've skipped over learning iOS in favor of RN.

I can confirm that this will compile into an archive after switching the Deployment Target following your instructions.

**Comment by jariwalabhavesh** [comment]
@technoplato : awesome
