### ISSUE TITLE
Custom controls support

### ISSUE THREAD

**Issue by jariwalabhavesh** [manse/react-native-brightcove-player#16]
We can create layer over player and add control by disabling internal controls. it is working fine with ios  but for android overlay workaround is not working. so if we have custom controls support internally that will be helpful. 
The only thing i stuck with is custom control in android. Any plan to add custom controls support ??

**Comment by manse** [comment]
I am also in trouble that can not overlay any elements on the player in Android.
I will contact if there is progress.

**Comment by manse** [comment]
I found that using `elevation` displays custom control over the brightcove player on android.

```
<BrightcovePlayer />
<View style={styles.control} />

const styles = StyleSheet.create({
  control: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 200,
    height: 200,
    backgroundColor: 'red',
    zIndex: 10000,
    elevation: 10000 // important
  },
}
```

![Screenshot_20190515-135146_example](https://user-images.githubusercontent.com/443965/57749364-b02a6680-7718-11e9-93aa-ace34b77d27b.jpg)

**Comment by jariwalabhavesh** [comment]
@manse : Thanks. I will try that
