### ISSUE TITLE
Support event for captions and method for switching video quality

### ISSUE THREAD

**Issue by jariwalabhavesh** [manse/react-native-brightcove-player#17]
@manse 
Thanks for great plugin, it is working super. 🥇 

I am looking for some additional events and attribute if plugin can support.

1. can i get support captions list(subtitles) and method to switch captions and also option to hide subtitle of videos. because if this attribute and event start supporting player then i can map it with custom control and show list of captions available and provide selection for that.

2. Also expecting support to get list of video quality(like: 280p, 480p, 710p) supported by video and allow to switch between them. If this attribute and switching event start supporting player then i can map it with custom controls.

**Comment by manse** [comment]
I have no plan to support subtitle lists or video qualities.
Pull requests welcome.
