### ISSUE TITLE
How to hide lock screen media  controls in ios

### ISSUE THREAD

**Issue by jariwalabhavesh** [manse/react-native-brightcove-player#18]
@manse 
If the video is playing and we lock our device then video will still continue to play and also show media control and they not working as well.

Is there a way to hide those lockscreen controls????

**Comment by manse** [comment]
I can not understand the situation. Can you record to show me that issue ?

**Comment by manse** [comment]
Is this ?
https://github.com/corbt/react-native-keep-awake

**Comment by jariwalabhavesh** [comment]
It's no more issue.
