### ISSUE TITLE
SDK 23 too low

### ISSUE THREAD

**Issue by rafbc** [manse/react-native-brightcove-player#19]
The SDK 23 is quite low at this stage. Consider upgrading it to 25, maybe the latest? :)

```The SDK Build Tools revision (23.0.1) is too low for project ':react-native-brightcove-player'. Minimum required is 25.0.0```

**Comment by manse** [comment]
That message is not appear in my project.
Please review the setting of your codes.

**Comment by rafbc** [comment]
Depends on what emulator you are using. Android SDK is up to the 28 now, and Google request the apps to be updated, so trying to run into anything more than 25, it will break.

This is where you are setting the sdk version.
https://github.com/manse/react-native-brightcove-player/blob/master/android/build.gradle
