### ISSUE TITLE
Not working on tvOS

### ISSUE THREAD

**Issue by samuelint** [manse/react-native-brightcove-player#20]
On tvOS the following message appear.

requirenativecomponent: "BrightcovePlayer" was not found in the uimanager

![image](https://user-images.githubusercontent.com/5473142/46926656-9c424900-cfff-11e8-8316-2f40962ee08d.png)

Any plan to make it work on tvOS?

**Comment by manse** [comment]
Sorry but I do not have plans to support tvOS. Pull request is welcome.
