### ISSUE TITLE
How do we change the styling / color of the seeekbar, etc?

### ISSUE THREAD

**Issue by technoplato** [manse/react-native-brightcove-player#21]

**Comment by manse** [comment]
You can not set the styling of the player seek bar.
Some props are provided for implementing a custom controller (`disableDefaultControl`, `onProgress`, etc).

**Comment by technoplato** [comment]
I know this is a long shot, but is there any way you could help me style the BrightCove player directly? 

That would be the difference between one or two lines of code and essentially recreating a control structure for the player.

I could pay you for your time.

**Comment by manse** [comment]
OK. I'll try to find the solution when I have time.

**Comment by technoplato** [comment]
Thank you so much. 

I need to be able to color the seekbar and change which buttons are present in the controls (toggle closed captions, RR and FF, and show only live appropriate controls)

**Comment by technoplato** [comment]
@manse is there any way we could work together on this today or tomorrow?

**Comment by manse** [comment]
@technoplato 
Sorry but I can not. Please make pull request yourself, or wait until releasing fixed version.
