### ISSUE TITLE
SSAI Plugin for the Native SDK for Android Media Controls Issue

### ISSUE THREAD

**Issue by gegis** [manse/react-native-brightcove-player#25]
We are using your module for Brightcove services.

We recently integrated SSAI on web side and doing it in Android app.
After following this document:
https://support.brightcove.com/ssai-plugin-native-sdk-android

We are experiencing the following issues:

If we use these versions:
    compile 'com.brightcove.player:exoplayer2:6.5.0'
    compile 'com.brightcove.player:android-ssai-plugin:6.7.0'
We have video controls but video time bar does not move and total time is 0

If we use these versions:
    compile 'com.brightcove.player:exoplayer2:6.7.0'
    compile 'com.brightcove.player:android-ssai-plugin:6.7.0'
Media controls with time bar completely disappear when the ad starts playing and never appear again, although if we change orientation - media controls re-appear, we tried many different ways for re-rendering and re-invoking media controls after the ad is complete, but no luck.

The app always launches in full screen, it feels like media controls are still within the parent, just after the ad starts playing - they never appear again.

We've tried there is no 6.5.0 version for SSAI plugin.

Could you please advise what could go wrong in this situation?

Thanks,
Egis

**Comment by manse** [comment]
I know that the implementation of media control is incomplete on Android (For example once in fullscreen view, the position of the media control will move).
I have no idea about solving this problem.
