### ISSUE TITLE
Example project issue

### ISSUE THREAD

**Issue by rafbc** [manse/react-native-brightcove-player#26]
Hey @manse,

Tried to run your app using the example but I get an error that might be associated with symlinking. How do you solve the issue? How do you actually run the app since react native doesn't support the linking file:.. you are using in the package.json?

Thanks

**Comment by manse** [comment]
Example app works correctly on my mac.
Replacing relative path with package name in package.json may work.
```
- "react-native-brightcove-player": "file:.."
+ "react-native-brightcove-player": "1.4.1"
```

**Comment by rafbc** [comment]
Yeah, I was just trying to make changes to the native part and see how it reflected in the example app, but apparently, it doesn't work. 

When using yarn install, it actually copies the files, instead of creating the symlink, so that's all good.
