### ISSUE TITLE
Does integrating this SDK setup make Brightcove 360 videos playable on RN?

### ISSUE THREAD

**Issue by tomball123** [manse/react-native-brightcove-player#31]
Hi, I'm trying to get 360 vids to work in my RN app.

The Brightcove documentation states that any app built with the Brightcove SDK has the ability to play 360 videos.

However, after implementing this SDK setup i've been unsuccessful in getting 360 videos to play.

Has anyone been successful in this/is it possible?

**Comment by manse** [comment]
Sorry but playing 360 video feature is not supported and it does not have any plans to support.
