### ISSUE TITLE
Support for Closed Caption and Edge to Edge video screen.

### ISSUE THREAD

**Issue by ronit-kadwane** [manse/react-native-brightcove-player#35]
Hello @manse ,

1. I need closed caption option in my application, Do I get support for closed caption option from this library. As Brightcove SDK supports Closed Caption feature.

2. Now mobile devices having different type of aspect ratio i.e. 21:9, 16:9, 18:9, 19:9, etc
but only 16:9 ratio devices covers the whole screen(edge to edge) for video.
Can I get support for other aspect ratios? or
How Can I manage for other aspect ratios?

Are you planning to support these two features?
If yes please let me know How much time it will take?

Hoping you will support it soon.
Thank you.

**Comment by ronit-kadwane** [comment]
@manse Are you planning to add the closed captioning feature in the library?

**Comment by manse** [comment]
Hello ronit,
I have no plan to support captions for the library.

---
> 2. Now mobile devices having different type of aspect ratio i.e. 21:9, 16:9, 18:9, 19:9, etc
but only 16:9 ratio devices covers the whole screen(edge to edge) for video.
Can I get support for other aspect ratios? or
How Can I manage for other aspect ratios?

There is no way to scale the video as large as possible without stretching to cover the video player. As a workaround, increase player width (`1000px` for example) and set css `position: absolute; left: ${(WINDOW_WIDTH - 1000) / 2}px;`

**Comment by ronit-kadwane** [comment]
@manse Thank you.
