### ISSUE TITLE
I'm wondering whether player can support background play

### ISSUE THREAD

**Issue by jsunwoo** [manse/react-native-brightcove-player#41]
Hi,

Thank you for your great support.
I'm using your package really well.

And also, I'm trying to play video(audio) in the background.
Is there a way that I can play in the background?
If I can play video in the background that would be great.

**Comment by manse** [comment]
Sorry but background playback is not supported.

**Comment by jsunwoo** [comment]
> Sorry but background playback is not supported.

Thank you for letting me know!
