### ISSUE TITLE
Error when finish playing a video on iOS

### ISSUE THREAD

**Issue by rafbc** [manse/react-native-brightcove-player#5]
Hi @manse 

I have found an issue on iOS.

When the video ends, it is throwing an error: https://ibb.co/jXFGYT

Do you have any clue on why this would happen?

**Comment by jariwalabhavesh** [comment]
@manse 
I had also face this issue with release 1.1.0

**Comment by manse** [comment]
@rafbrightcove @jariwalabhavesh 
Thanks for the report.
The issue was fixed in the latest release 1.2.0.
