### ISSUE TITLE
Brigthcove OnceUX or IMA

### ISSUE THREAD

**Issue by rafbrightcove** [manse/react-native-brightcove-player#6]
Hey @manse 

Trying to implement the different [SDK](https://github.com/brightcove/BrightcoveSpecs) into the player. Would you be able to comment if it is possible to use the Brightcove-Player-OnceUX or Brightcove-Player-IMA instead of the "Core" one? And how would i do that?

Thanks

**Comment by manse** [comment]
@rafbrightcove 

As a result of survey, OnceUX or IMA seem to be plugins related to advertisement. We can not use them instead of the Core player.
If you would like to use these plugins please issue a pull request.
