### ISSUE TITLE
ARC Semantic Issue Group: No visible @interface for 'BCOVOfflineVideoManager' declares the selector 'requestVideoDownload:parameters:completion'

### ISSUE THREAD

**Issue by slava-the-skills** [manse/react-native-brightcove-player#71]
ARC Semantic Issue Group: ```No visible @interface for 'BCOVOfflineVideoManager' declares the selector 'requestVideoDownload:parameters:completion'.```

<img width="266" alt="Снимок экрана 2021-03-29 в 11 42 53" src="https://user-images.githubusercontent.com/81310419/112810646-e8748d00-9083-11eb-9432-af19f0001517.png">

Environment:
"react-native": "~0.63.4"
pods: 1.10.1
xcode: 12.4

Added `source 'https://github.com/brightcove/BrightcoveSpecs.git'`

**Comment by slava-the-skills** [comment]
Solved
1. Add `"${PODS_ROOT}/Brightcove-Player-Core/ios/dynamic/BrightcovePlayerSDK.framework/Headers"` to the Header Search Paths
2. `pod update`
3. Clean build

**Comment by nlabofa** [comment]
hi @slava-the-skills i'm experiencing this error and your solution isn't working

**Comment by anhkieet** [comment]
> hi @slava-the-skills i'm experiencing this error and your solution isn't working

Have you solved this issue?

**Comment by anhkieet** [comment]
Fixed by adding mediaSelections:nil

`[[BrightcovePlayerOfflineVideoManager sharedManager] requestVideoDownload:video mediaSelections:nil parameters:[self generateDownloadParameterWithBitRate:bitRate] completion:^(BCOVOfflineVideoToken offlineVideoToken, NSError *error) {
            if (error) {
                reject(kErrorCode, error.description, error);
                return;
            }
            [NSUserDefaults.standardUserDefaults setObject: @{kUserDefaultKeyOfflineAccountId: accountId,
                                                              kUserDefaultKeyOfflineVideoId: video.properties[kBCOVVideoPropertyKeyId]
                                                              }
                                                    forKey:[kUserDefaultKeyOfflinePrefix stringByAppendingString:offlineVideoToken]];
            [NSUserDefaults.standardUserDefaults synchronize];
            [self sendOfflineNotification];
            resolve(offlineVideoToken);
        }];`
